spring:
  h2:
    console:
      enabled: false
  datasource:
    password: sa@newad2026

management:
  endpoints:
    access:
      default: none

logging:
  level:
    root: INFO
    au.com.newad.web: INFO