DROP TABLE IF EXISTS article;
CREATE TABLE article (
    PK_ID bigint NOT NULL AUTO_INCREMENT,
    TITLE varchar(100) NOT NULL,
    SUMMARY varchar(1000) DEFAULT NULL,
    PIC_URL varchar(1000) DEFAULT NULL,
    TOP_IN_CATEGORY varchar(10) DEFAULT NULL,
    TOP_IN_CATEGORY_ORDER int DEFAULT NULL,
    TOP_IN_SITE varchar(10) DEFAULT NULL,
    TOP_IN_SITE_ORDER int DEFAULT NULL,
    TIME_PUBLISHED datetime NOT NULL,
    CLICK_NUMBER int NOT NULL DEFAULT '0',
    FK_CATEGORY_ID bigint NOT NULL,
    PRIMARY KEY (PK_ID),
    UNIQUE KEY PK_ID_UNIQUE_ARTICLE (PK_ID)
);

DROP TABLE IF EXISTS article_content;
CREATE TABLE article_content (
    PK_ID bigint NOT NULL AUTO_INCREMENT,
    FK_ARTICLE_ID bigint NOT NULL,
    CONTENT mediumtext,
    PRIMARY KEY (PK_ID),
    UNIQUE KEY PK_ID_UNIQUE_ARTICLE_CONTENT (PK_ID)
);

DROP TABLE IF EXISTS category;
CREATE TABLE IF NOT EXISTS category (
    PK_ID bigint NOT NULL AUTO_INCREMENT,
    SHORT_NAME varchar(45) NOT NULL,
    LONG_NAME varchar(100) DEFAULT NULL,
    PARENT_ID bigint NOT NULL,
    SEQUENCE smallint NOT NULL DEFAULT '0',
    PIC_URL varchar(400) DEFAULT NULL,
    DESCRIPTION varchar(1000) DEFAULT NULL,
    PRIMARY KEY (PK_ID),
    UNIQUE KEY PK_ID_UNIQUE_CATEGORY (PK_ID)
);